export enum MenuUrl {
  LOGIN = 'Login',
  HOME = 'Home',
  Menu = 'Menu',
  CREATE_USER = 'CreateUser',
  SPLASH = 'Splash',
  Exam = 'Exam',
  Profile = 'Profile',
  News = 'News',
  NewsDetails = 'NewsDetails',
  Suport = 'Suport',
  Translation = 'Translation',
  Discipline = 'Discipline',
  DisciplineCreation = 'DisciplineCreationScreen',
  Dashboard = 'Dashboard',
  ExamDetails = 'ExamDetails',
}
