export enum MenuUrl {
  LOGIN = 'Login',
  HOME = 'Home',
  Menu = 'Menu',
  CREATE_USER = 'CreateUser',
  SPLASH = 'Splash',
  Exam = 'Exam',
  Profile = 'Profile',
  News = 'News',
  NewsDetails = 'NewsDetails',
  Suport = 'Suport',
  Translation = 'Translation',
  Discipline = 'Discipline',
  DisciplineCreation = 'DisciplineCreationScreen',
  DisciplineMenu = 'DisciplineMenu',
  DisciplineDetails = 'DisciplineDetails',
  Dashboard = 'Dashboard',
  ExamDetails = 'ExamDetails',
  FilesAndPhotos = 'FilePhotos',
  PasswordRecovery = 'PasswordRecovery',
  Absences = 'AbsencesScreen',
  AbsencesMenu = 'AbsencesMenu',
}
